Repository super-coffee/coffee-keys, pull requests merged in 2020-04, with the labels that each got.

#1 将中文和英文的README分开
  README.md
  README_en.md
Labels: documentation

#2 实现了 updateInfo
  server/coffee-keys.py
  server/database.py
Labels: enhancement

#5 Fixed #4，改进错误页面
  web/error/err.html
  web/error/normalize.css
  web/error/rymd.css
  web/error/single-error-page.html
  web/js/updateInfo.js
  web/updateInfo.html
Labels: bug

#7 fixed #6
  server/database.py
Labels: bug

#9 完成基本功能
  README.md
  README_en.md
  SECURITY.md
  server/coffee-keys.py
  server/database.py
  server/errors.py
  web/error/normalize.css
  web/error/normalize.min.css
  web/error/rymd.css
  web/error/rymd.js
  web/error/single-error-page.html
  web/index.html
  web/js/login.js
  web/js/newKey.js
  web/js/searchKey.js
  web/js/showMsg.js
  web/js/updateInfo.js
  web/login.html
  web/newKey.html
  web/searchKey.html
  web/updateInfo.html
Labels: enhancement
